id: P663FB07F
initial_creation_type: input
source_metadata:
  title: Lhatsün Namkha Jigme Series
  language: zh
  description: 'Texts associated with the famous yogi Lhatsün Namkha Jigme (lha btsun
    nam mkha'' ''jigs med, 1597–1650), who is credited with ''opening the hidden land''
    of Sikkim:'
  volume:
    394682b3db664d85b5ec0b4b9cdbee46:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    ca1d4100ff6348a6b64cdf884f312d26:
      title: Summoning Prosperity
      parent: Prayers and Practices
    0331516d135b4dd4b9ba4244024efc84:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Sang Offering
    57bd68bf53464fcfb959332a6618d502:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Sang Offering
    3bde140bff994e689264c8251fc1c595:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
created_at: '2022-03-01T00:35:25.498624'
last_modified_at: '2022-03-01T00:35:25.498626'
